# Generated by Django 6.0.5 on 2026-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_ruta_aliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='disponible',
            field=models.BooleanField(default=False, help_text='¿Disponible para recibir nuevas rutas?'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, help_text='Última conexión registrada', null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='ultima_ubicacion',
            field=models.JSONField(blank=True, default=dict, help_text="Última ubicación: {'lat': ..., 'lng': ...}"),
        ),
    ]
